apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
  namespace: ft-services
data:
  datasources.yaml: |+
    apiVersion: 1
    datasources:
    - name: InfluxDB
      type: influxdb
      # proxy or direct (Server or Browser in the UI)
      access: proxy
      url: "http://$INFLUXDB_HOST$INFLUXDB_HTTP_BIND_ADDRESS"
      password: $INFLUXDB_PASS
      user: $INFLUXDB_USER
      database: $INFLUXDB_DB
  providers.yaml: |+
    apiVersion: 1
    providers:
    - name: dashboards
      orgId: 1
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      options:
        path: /usr/share/grafana/public/dashboards
        foldersFromFilesStructure: true
