apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource-config
  namespace: ft-services
data:
  datasource.yaml: |+
    apiVersion: 1
    datasources:
      - name: InfluxDB
        type: influxdb
        # proxy or direct (Server or Browser in the UI)
        access: proxy
        url: http://influxdb:8086
