apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-config
  namespace: ft-services
data:
  # Config file
  influxdb.conf: |+
    reporting-disabled = true

    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"
    
    [admin]
      enabled = false

    [http]
      enabled = true
      bind-address = ":8086"
      auth-enabled = false

    [tls]
      min-version = "tls1.2"
      max-version = "tls1.3"
