apiVersion: v1
kind: ConfigMap
metadata:
  name: mariadb-config
  namespace: dev
data:
  # Config file
  my.cnf: |
    # This group is read both both by the client and the server
    # use it for options that affect everything
    [client-server]
    port   = 3306
    socket = /run/mysqld/mysqld.sock

    # This group is read by the server
    [mysqld]
    user            = root
    port            = 3306
    socket          = /run/mysqld/mysqld.sock
    datadir         = /var/lib/mysql
    pid-file        = /run/mysqld/mysqld.pid

    # Disabling symbolic-links is recommended to prevent assorted security risks
    symbolic-links=0
