apiVersion: v1
kind: ConfigMap
metadata:
  name: metallb-config
  namespace: metallb-system
data:
  config: |
    address-pools:
    - name: ft-services-net
      protocol: layer2
      addresses:
      - 192.168.49.1-192.168.49.254
