apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-config
  namespace: ft-services
data:
  # Config file
  telegraf.conf: |+
    # Global tags can be specified here in key="value" format.
    [global_tags]

    # Configuration for telegraf agent
    [agent]
      ## Default data collection interval for all inputs
      interval = "10s"
      ## Rounds collection interval to 'interval'
      round_interval = true

      ## Telegraf will send metrics to outputs in batches of at most
      ## metric_batch_size metrics.
      ## This controls the size of writes that Telegraf sends to output plugins.
      metric_batch_size = 1000

      ## For failed writes, telegraf will cache metric_buffer_limit metrics for each
      ## output, and will flush this buffer on a successful write. Oldest metrics
      ## are dropped first when this buffer fills.
      ## This buffer only fills when writes fail to output plugin(s).
      metric_buffer_limit = 10000

      ## Collection jitter is used to jitter the collection by a random amount.
      ## Each plugin will sleep for a random time within jitter before collecting.
      ## This can be used to avoid many plugins querying things like sysfs at the
      ## same time, which can have a measurable effect on the system.
      collection_jitter = "0s"

      ## Default flushing interval for all outputs. Maximum flush_interval will be
      ## flush_interval + flush_jitter
      flush_interval = "10s"
      ## Jitter the flush interval by a random amount. This is primarily to avoid
      ## large write spikes for users running a large number of telegraf instances.
      ## ie, a jitter of 5s and interval 10s means flushes will happen every 10-15s
      flush_jitter = "0s"

      ## Run telegraf with debug log messages.
      debug = false
      ## Run telegraf in quiet mode (error log messages only).
      quiet = false
      ## Specify the log file name. The empty string means to log to stderr.
      logtarget = "file"
      logfile = "/var/log/telegraf/telegraf.log"

      ## Override default hostname, if empty use os.Hostname()
      hostname = "$HOSTNAME"
      ## If set to true, do no set the "host" tag in the telegraf agent.
      omit_hostname = false

    # Configuration for sending metrics to InfluxDB
    [[outputs.influxdb]]
      urls = ["http://$INFLUXDB_HOST$INFLUXDB_PORT"]
      ## The target database for metrics; will be created as needed.
      database = "$INFLUXDB_DB"
      skip_database_creation = false

      ## HTTP Basic Auth
      username = "$INFLUXDB_USER"
      password = "$INFLUXDB_PASS"

    # Read metrics about cpu usage
    [[inputs.cpu]]
      ## Whether to report per-cpu stats or not
      percpu = true
      ## Whether to report total system cpu stats or not
      totalcpu = true
      ## If true, collect raw CPU time metrics.
      collect_cpu_time = false
      ## If true, compute and report the sum of all non-idle CPU states.
      report_active = false

    # Read metrics about disk usage by mount point
    [[inputs.disk]]
      ## Ignore mount points by filesystem type.
      ignore_fs = ["tmpfs", "devtmpfs", "devfs"]

    # Read metrics about disk IO by device
    [[inputs.diskio]]

    # Get kernel statistics from /proc/stat
    [[inputs.kernel]]

    # Read metrics about memory usage
    [[inputs.mem]]

    # Get the number of processes and group them by status
    [[inputs.processes]]

    # Read metrics about swap memory usage
    [[inputs.swap]]

    # Read metrics about system load & uptime
    [[inputs.system]]

    # Read metrics about docker containers
    [[inputs.docker]]
    endpoint = "unix:///var/run/docker.sock"
