apiVersion: v1
kind: ConfigMap
metadata:
  name: vsftpd-config
  namespace: ft-services
data:
  # Config file for server
  vsftpd.conf: |
    ########################################
    #                                      #
    #  Global VSFTPD server configuration  #
    #                                      #
    ########################################

    # Standalone mode
    listen=YES

    # Ports
    listen_port=21
    # Make sure PORT transfer connections originate from port 20 (ftp-data)
    connect_from_port_20=YES

    # This string is the name of the PAM service vsftpd will use
    pam_service_name=vsftpd

    # Info
    ftpd_banner="Welcome"
    dirmessage_enable=YES

    # Anonymous FTP
    anonymous_enable=NO
    anon_umask=002
    anon_mkdir_write_enable=NO
    anon_root=/var/lib/ftp
    anon_world_readable_only=NO

    # User list
    userlist_enable=YES
    userlist_file=/etc/vsftpd/vsftpd.user_list
    userlist_deny=YES

    # Local users
    chroot_local_user=YES
    allow_writeable_chroot=YES

    # Controls whether local logins are permitted or not
    local_enable=YES
    local_umask=022

    # Limits for standalone mode
    max_clients=10
    max_per_ip=4
    max_login_fails=3

    # Activate logging of uploads/downloads
    xferlog_enable=YES
    xferlog_file=/var/log/vsftpd.log

    # Sandboxing
    seccomp_sandbox=NO

    # Passive mode
    pasv_enable=YES
    pasv_addr_resolve=YES
    #pasv_address=ftps.ft-services.svc.cluster.local
    # The minimum port to allocate for PASV style data connections.
    pasv_min_port=21000
    # The maximum port to allocate for PASV style data connections.
    pasv_max_port=21100

    ########################################
    #                                      #
    #           SSL configuration          #
    #                                      #
    ########################################

    ssl_enable=YES
    debug_ssl=YES

    allow_anon_ssl=NO
    force_local_data_ssl=NO
    force_local_logins_ssl=NO

    # Permit TLS v1 protocol connections. TLS v1 connections are preferred
    ssl_tlsv1=YES
    ssl_sslv2=NO
    ssl_sslv3=NO

    # Additional protection against Man In The Middle (MITM) attacks.
    # This may not be compatible with some older FTP clients.
    require_ssl_reuse=NO

    # Require the server to use stronger cipher suites.
    #ssl_ciphers=HIGH

    # This option specifies the location of the RSA certificate to use for SSL
    # encrypted connections.
    rsa_cert_file=/etc/ssl/certs/vsftpd-selfsigned.crt
    rsa_private_key_file=/etc/ssl/private/vsftpd-selfsigned.key

    ########################################
    #                                      #
    #         Users configuration          #
    #                                      #
    ########################################

    user_config_dir=/etc/vsftpd/vsftpd_user_conf

  # User list
  vsftpd.user_list: |
    root

  # Config file for user42
  user42: |
    ########################################
    #                                      #
    #          user42 configuration        #
    #                                      #
    ########################################

    # Set local root
    local_root=/home/user42/files

    # Uncomment this to enable any form of FTP write command.
    write_enable=YES
