apiVersion: v1
kind: ConfigMap
metadata:
  name: vsftpd-config
  namespace: ft-services
data:
  # Config file for server
  vsftpd.conf: |
    ########################################
    #                                      #
    #  Global VSFTPD server configuration  #
    #                                      #
    ########################################

    # Standalone mode
    listen=YES
    # Sandboxing
    seccomp_sandbox=NO

    # Ports
    listen_port=21
    # Make sure PORT transfer connections originate from port 20 (ftp-data)
    connect_from_port_20=YES

    # This string is the name of the PAM service vsftpd will use
    pam_service_name=vsftpd

    # Info
    ftpd_banner=Welcome
    dirmessage_enable=YES
    use_localtime=YES

    # Write rights
    write_enable=YES

    # Local users
    local_enable=YES
    local_umask=022

    # Anonymous FTP
    anonymous_enable=NO

    # Activate logging of uploads/downloads
    dual_log_enable=YES
    xferlog_enable=YES
    xferlog_file=/var/log/xferlog
    log_ftp_protocol=YES
    vsftpd_log_file=/var/log/vsftpd.log

    # Passive mode
    pasv_enable=YES
    pasv_address=192.168.49.2
    pasv_min_port=20000
    pasv_max_port=20001

    ########################################
    #                                      #
    #           SSL configuration          #
    #                                      #
    ########################################

    ssl_enable=YES
    debug_ssl=NO

    allow_anon_ssl=NO
    force_local_data_ssl=YES
    force_local_logins_ssl=YES
    require_ssl_reuse=NO

    # Permit TLS v1 protocol connections. TLS v1 connections are preferred
    ssl_tlsv1=YES
    ssl_sslv2=NO
    ssl_sslv3=NO

    # Require the server to use stronger cipher suites.
    ssl_ciphers=HIGH

    # This option specifies the location of the RSA certificate to use for SSL
    # encrypted connections.
    rsa_cert_file=/etc/ssl/certs/vsftpd-selfsigned.crt
    rsa_private_key_file=/etc/ssl/private/vsftpd-selfsigned.key
