apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ft-services
  labels:
    app: nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: ip-ext
spec:
  ports:
    - port: 80
      targetPort: http-port
      protocol: TCP
      name: http
    - port: 443
      targetPort: https-port
      protocol: TCP
      name: https
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: ft-services
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:ft
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http-port
        - containerPort: 443
          name: https-port
