FROM alpine:3.13

LABEL maintainer="mboivin@student.42.fr"

# Environment Variables
ENV GRAFANA_VERSION=7.4.3

# Install necessary packages
RUN apk add --no-cache

# Inform which ports are intended to be published
EXPOSE 3000
