apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: ft-services
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
      targetPort: mariadb-port
      protocol: TCP
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb
  namespace: ft-services
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  updateStrategy:
    type: RollingUpdate
  serviceName: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      restartPolicy: Always
      containers:
      - name: mariadb
        image: mariadb:ft
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: wordpress-db-config
        - secretRef:
            name: wordpress-db-creds
        ports:
        - containerPort: 3306
          name: mariadb-port
        volumeMounts:
        - name: mariadb-data
          mountPath: /var/lib/mysql
        - name: mariadb-conf-vol
          mountPath: /etc/my.cnf
          subPath: my.cnf
          readOnly: true
      volumes:
      - name: mariadb-conf-vol
        configMap:
          name: mariadb-config
  volumeClaimTemplates:
  - metadata:
      name: mariadb-data
      namespace: ft-services
      labels:
        app: mariadb
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
