apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ft-services
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: mysql-port
      protocol: TCP
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ft-services
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  updateStrategy:
    type: RollingUpdate
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
      - name: mysql
        image: mysql:ft
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: wordpress-db-config
        - secretRef:
            name: wordpress-db-creds
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        - name: mysql-conf-vol
          mountPath: /etc/my.cnf
          subPath: my.cnf
          readOnly: true
      volumes:
      - name: mysql-conf-vol
        configMap:
          name: mysql-config
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      namespace: ft-services
      labels:
        app: mysql
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
