apiVersion: v1
kind: Service
metadata:
  name: ftps
  namespace: ft-services
  labels:
    app: vsftpd
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  ports:
  - port: 21
    targetPort: ftp-port
    protocol: TCP
    name: control
  - port: 20
    targetPort: ftp-data-port
    protocol: TCP
    name: data
  selector:
    app: vsftpd
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  namespace: ft-services
  labels:
    app: vsftpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vsftpd
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: vsftpd
    spec:
      restartPolicy: Always
      containers:
      - name: ftps
        image: ftps:ft
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftp-port
        - containerPort: 20
          name: ftp-data-port
        volumeMounts:
        - name: vsftpd-conf-vol
          mountPath: /etc/vsftpd/vsftpd.conf
          subPath: vsftpd.conf
          readOnly: true
        - name: vsftpd-conf-vol
          mountPath: /etc/vsftpd/vsftpd.user_list
          subPath: vsftpd.user_list
          readOnly: true
        - name: vsftpd-conf-vol
          mountPath: /etc/vsftpd/vsftpd_user_conf/user42
          subPath: user42
          readOnly: true
      volumes:
      - name: vsftpd-conf-vol
        configMap:
          name: vsftpd-config
