apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  namespace: ft-services
  annotations: 
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  ports:
  - port: 21
    targetPort: listen-port
    protocol: TCP
    name: ftp
  - port: 21000
    targetPort: pasv-min-port
    protocol: TCP
    name: ftp-pasv-min
  - port: 21100
    targetPort: pasv-max-port
    protocol: TCP
    name: ftp-pasv-max
  selector:
    app: ftps-server
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps-server
    spec:
      containers:
      - image: ftps:ft
        name: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: listen-port
        - containerPort: 21000
          name: pasv-min-port
        - containerPort: 21100
          name: pasv-max-port
