apiVersion: v1
kind: Service
metadata:
  name: ftps
  namespace: ft-services
  labels:
    app: ftps
spec:
  type: LoadBalancer
  ports:
  - port: 21
    targetPort: ftps-port
    protocol: TCP
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  namespace: ft-services
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - image: ftps:ft
          name: ftps
          imagePullPolicy: Never
          #env:
          ports:
            - containerPort: 21
              name: ftps-port
          volumeMounts:
            - mountPath: /var/ftp
