apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: ft-services
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  ports:
  - port: 3000
    targetPort: grafana-port
    protocol: TCP
  selector:
    app: grafana
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deployment
  namespace: ft-services
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: frontend
    spec:
      containers:
      - image: grafana:ft
        name: grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana-port
