apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: ft-services
  labels:
    app: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  ports:
  - port: 3000
    targetPort: grafana-port
    protocol: TCP
  selector:
    app: grafana
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: ft-services
  labels:
    app: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - image: grafana:ft
        name: grafana
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: grafana-creds
        ports:
        - containerPort: 3000
          name: grafana-port
        volumeMounts:
        - name: grafana-vol
          mountPath: /var/lib/grafana
        - name: grafana-datasource-vol
          mountPath: /etc/grafana/provisioning/datasources/datasource.yaml
          subPath: datasource.yaml
          readOnly: true
        - name: grafana-dashboards-vol
          mountPath: /etc/grafana/provisioning/dashboards
          readOnly: true
      volumes:
      - name: grafana-vol
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: grafana-datasource-vol
        configMap:
          name: grafana-datasource-config
          items:
          - key: "datasource.yaml"
            path: "datasource.yaml"
      - name: grafana-dashboards-vol
        configMap:
          name: grafana-dashboards-config
