apiVersion: v1
kind: Service
metadata:
  name: influxdb-svc
  namespace: ft-services
  labels:
    app: influxdb
spec:
  ports:
  - port: 8086
    targetPort: influxdb-port
    protocol: TCP
    name: api
  selector:
    app: influxdb
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
  namespace: ft-services
  labels:
    app: influxdb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deploy
  namespace: ft-services
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb:ft
        name: influxdb
        imagePullPolicy: Never
        env:
        - name: INFLUXDB_DB
          valueFrom:
            configMapKeyRef:
              name: influxdb-config
              key: INFLUXDB_DB
        envFrom:
        - secretRef:
            name: influxdb-creds
        ports:
        - containerPort: 8086
          name: influxdb-port
        volumeMounts:
        - name: influxdb-data
          mountPath: /var/lib/influxdb
        - name: influxdb-conf-vol
          mountPath: /etc/influxdb/influxdb.conf
          subPath: influxdb.conf
          readOnly: true
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-pvc
      - name: influxdb-conf-vol
        configMap:
          name: influxdb-config
          items:
          - key: influxdb.conf
            path: influxdb.conf
