apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: ft-services
  labels:
    app: influxdb
spec:
  ports:
  - port: 8086
    targetPort: influxdb-port
    protocol: TCP
    name: api
  selector:
    app: influxdb
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: influxdb
  namespace: ft-services
  labels:
    app: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  serviceName: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      restartPolicy: Always
      containers:
      - image: influxdb:ft
        name: influxdb
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: monitoring-db-config
        - secretRef:
            name: influxdb-creds
        ports:
        - containerPort: 8086
          name: influxdb-port
        volumeMounts:
        - name: influxdb-conf-vol
          mountPath: /etc/influxdb/influxdb.conf
          subPath: influxdb.conf
          readOnly: true
        - name: influxdb-data
          mountPath: /var/lib/influxdb
      volumes:
      - name: influxdb-conf-vol
        configMap:
          name: influxdb-config
  volumeClaimTemplates:
  - metadata:
      name: influxdb-data
      namespace: ft-services
      labels:
        app: influxdb
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
