apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: ft-services
spec:
  ports:
  - port: 8086
    targetPort: influxdb-port
    protocol: TCP
    name: api
  selector:
    app: grafana
    tier: backend
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  namespace: ft-services
  labels:
    app: grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-deployment
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: grafana
        tier: backend
    spec:
      containers:
      - image: influxdb:ft
        name: influxdb
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: influxdb-secrets
        ports:
        - containerPort: 8086
          name: influxdb-port
        volumeMounts:
        - mountPath: /var/lib/influxdb
          name: influxdb-data
        - mountPath: /etc/influxdb
          name: influxdb-config
          subPath: influxdb.conf
          readOnly: true
      volumes:
      - name: influxdb-data
        persistentVolumeClaim:
          claimName: influxdb-pv-claim
      - name: influxdb-config
        configMap:
          name: influxdb-config
