apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: ft-services
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: mysql-port
      protocol: TCP
  selector:
    app: mysql
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: ft-services
  labels:
    app: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: ft-services
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:ft
        name: mysql
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: mysql-wp-config
        - secretRef:
            name: mysql-wp-creds
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc
