apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: ft-services
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
      targetPort: mysql-port
      protocol: TCP
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: ft-services
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  serviceName: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:ft
        name: mysql
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: mysql-wp-config
        - secretRef:
            name: mysql-wp-creds
        ports:
        - containerPort: 3306
          name: mysql-port
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-data
      namespace: ft-services
      labels:
        app: mysql
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 2Gi
