apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: ft-services
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  ports:
    - port: 80
      targetPort: http-port
      protocol: TCP
      name: http
    - port: 443
      targetPort: https-port
      protocol: TCP
      name: https
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:ft
        name: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: http-port
        - containerPort: 443
          name: https-port
