apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ft-services
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: nginx-http-port
      protocol: TCP
      name: http
    - port: 443
      targetPort: nginx-https-port
      protocol: TCP
      name: https
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx:ft
        name: nginx
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: nginx-http-port
        - containerPort: 443
          name: nginx-https-port
