apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: ft-services
  labels:
    app: nginx
spec:
  ports:
    - port: 80
      protocol: TCP
      name: http
    - port: 443
      protocol: TCP
      name: https
  selector:
    app: nginx
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:ft
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        - containerPort: 443
