apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: ft-services
  labels:
    app: phpmyadmin
spec:
  ports:
    - port: 5000
  selector:
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: ft-services
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin:ft
        imagePullPolicy: Never
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: wordpress_db_pass
        - name: PMA_HOST
          value: mysql
        - name: PMA_PORT
          value: "3306"
        ports:
        - containerPort: 5000
          name: phpmyadmin
