apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  namespace: ft-services
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  ports:
    - port: 5000
      targetPort: phpmyadmin-port
      protocol: TCP
  selector:
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin:ft
        name: phpmyadmin
        imagePullPolicy: Never
        env:
        - name: PMA_HOST
          value: mysql-svc
        - name: PMA_PORT
          value: "3306"
        envFrom:
        - configMapRef:
            name: mysql-wp-config
        - secretRef:
            name: mysql-wp-secrets
        ports:
        - containerPort: 5000
          name: phpmyadmin-port
