apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  namespace: ft-services
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  ports:
    - port: 5000
      targetPort: phpmyadmin-port
      protocol: TCP
  selector:
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: ft-services
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin:ft
        name: phpmyadmin
        imagePullPolicy: Never
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-wp-config
              key: MYSQL_DATABASE
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-wp-config
              key: MYSQL_ROOT_HOST
        - name: PMA_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-wp-config
              key: MYSQL_ROOT_PORT
        envFrom:
        - secretRef:
            name: mysql-wp-creds
        ports:
        - containerPort: 5000
          name: phpmyadmin-port
        volumeMounts:
        - name: pma-conf-vol
          mountPath: /var/www/phpmyadmin/config.inc.php
          subPath: config.inc.php
          readOnly: true
        - name: php-conf-vol
          mountPath: /etc/php7/php-fpm.d/www.conf
          subPath: www.conf
          readOnly: true
        - name: php-conf-vol
          mountPath: /etc/php7/php-fpm.conf
          subPath: php-fpm.conf
          readOnly: true
      volumes:
      - name: pma-conf-vol
        configMap:
          name: phpmyadmin-config
          items:
          - key: "config.inc.php"
            path: "config.inc.php"
      - name: php-conf-vol
        configMap:
          name: php-config
          items:
          - key: "php-fpm.conf"
            path: "php-fpm.conf"
          - key: "www.conf"
            path: "www.conf"
