apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin-svc
  namespace: ft-services
  labels:
    app: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  ports:
    - port: 5000
      targetPort: phpmyadmin-port
      protocol: TCP
  selector:
    app: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deploy
  namespace: ft-services
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin:ft
        name: phpmyadmin
        imagePullPolicy: Never
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-wp-config
              key: MYSQL_DATABASE
        - name: PMA_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-wp-config
              key: MYSQL_ROOT_HOST
        - name: PMA_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-wp-config
              key: MYSQL_ROOT_PORT
        envFrom:
        - secretRef:
            name: mysql-wp-creds
        ports:
        - containerPort: 5000
          name: phpmyadmin-port
