apiVersion: v1
kind: Service
metadata:
  name: telegraf-svc
  namespace: ft-services
  labels:
    app: telegraf
spec:
  ports:
  - port: 8125
    targetPort: telegraf-port
    protocol: UDP
    name: statsd
  selector:
    app: telegraf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deploy
  namespace: ft-services
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: telegraf:ft
        name: telegraf
        imagePullPolicy: Never
        env:
        - name: INFLUXDB_URL
          valueFrom:
            configMapKeyRef:
              name: influxdb-config
              key: INFLUXDB_URL
        - name: INFLUXDB_DB
          valueFrom:
            configMapKeyRef:
              name: influxdb-config
              key: INFLUXDB_DB
        envFrom:
        - secretRef:
            name: influxdb-creds
        ports:
        - containerPort: 8125
          name: telegraf-port
        volumeMounts:
        - name: telegraf-conf-vol
          mountPath: /etc/telegraf/telegraf.conf
          subPath: telegraf.conf
          readOnly: true
      volumes:
      - name: telegraf-conf-vol
        configMap:
          name: telegraf-config
 