apiVersion: v1
kind: Service
metadata:
  name: telegraf-service
  namespace: ft-services
spec:
  ports:
  - port: 8125
    targetPort: telegraf-port
    protocol: UDP
    name: statsd
  selector:
    app: telegraf
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: telegraf:ft
        name: telegraf
        imagePullPolicy: Never
        envFrom:
        - secretRef:
            name: influxdb-secrets
        ports:
        - containerPort: 8125
          name: telegraf-port
        volumeMounts:
        - mountPath: /etc/telegraf/telegraf.conf
          name: telegraf-config
          subPath: telegraf.conf
          readOnly: true
      volumes:
      - name: telegraf-config
        configMap:
          name: telegraf-config
 