apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - image: telegraf:ft
        name: telegraf
        imagePullPolicy: Never
    volumes:
    - name: telegraf-config
      configMap:
        name: telegraf-config
