apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: ft-services
  labels:
    app: wordpress
  annotations:
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: wp-port
      protocol: TCP
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: ft-services
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:ft
        name: wordpress
        imagePullPolicy: Never
        env:
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: wordpress-db-config
              key: MYSQL_DATABASE
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: wordpress-db-creds
              key: MYSQL_USER
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-db-creds
              key: MYSQL_PASSWORD
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: wordpress-db-config
              key: MYSQL_ROOT_HOST
        - name: WORDPRESS_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: wordpress-db-config
              key: MYSQL_ROOT_PORT
        ports:
        - containerPort: 5050
          name: wp-port
        volumeMounts:
        - name: wp-conf-vol
          mountPath: /var/www/wordpress/wp-config.php
          subPath: wp-config.php
          readOnly: true
        - name: php-fpm-conf-vol
          mountPath: /etc/php7/php-fpm.d/www.conf
          subPath: www.conf
          readOnly: true
        - name: php-fpm-conf-vol
          mountPath: /etc/php7/php-fpm.conf
          subPath: php-fpm.conf
          readOnly: true
      volumes:
      - name: wp-conf-vol
        configMap:
          name: wordpress-config
      - name: php-fpm-conf-vol
        configMap:
          name: php-fpm-config
