apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  namespace: ft-services
  annotations: 
    metallb.universe.tf/allow-shared-ip: single-ip
spec:
  type: LoadBalancer
  ports:
    - port: 5050
      targetPort: wordpress-port
      protocol: TCP
  selector:
    app: wordpress
    tier: frontend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  namespace: ft-services
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: ft-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
      - image: wordpress:ft
        name: wordpress
        imagePullPolicy: Never
        env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: wordpress_db_pass
        ports:
        - containerPort: 5050
          name: wordpress-port
