apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: ft-services-net
      protocol: layer2
      addresses:
      - 192.168.49.2/25
