apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: telegraf
  namespace: ft-services
  labels:
    app: telegraf
spec:
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      restartPolicy: Always
      containers:
        - image: telegraf:ft
          name: telegraf
          imagePullPolicy: Never
          env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          envFrom:
          - configMapRef:
              name: monitoring-db-config
          - secretRef:
              name: influxdb-creds
          volumeMounts:
          - name: docker-socket
            mountPath: /var/run/docker.sock
          - name: telegraf-conf-vol
            mountPath: /etc/telegraf/telegraf.conf
            subPath: telegraf.conf
            readOnly: true
      volumes:
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
      - name: telegraf-conf-vol
        configMap:
          name: telegraf-config
