name: linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'k8s-lint'
        uses: azure/k8s-lint@v1
        with:
          manifests: |
              srcs/manifests/00-namespace.yaml
              srcs/manifests/configmaps/influxdb-config.yaml
              srcs/manifests/configmaps/metallb-config.yaml
              srcs/manifests/services/mysql.yaml
              srcs/manifests/services/nginx.yaml
              srcs/manifests/services/phpmyadmin.yaml
              srcs/manifests/services/wordpress.yaml
              srcs/manifests/secrets/wordpress-db.yaml
